apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-nginx
    app.kubernetes.io/managed-by: Helm
  name: demo-nginx
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-nginx
status:
  loadBalancer: {}
